:sectnums:
:toc: left
= limebike docs


== 系统的组成

=== 车辆组成
三类车辆 bike ebike 和 scooter

bike组成:U型锁、长条锂电池、太阳能板、其他常见部件

ebike组成: U型锁、长条锂电池、电控、大电池、电机、力矩传感器、其他常见部件

scooter 组成： 中控、电控、电机、大电池、以及其他常见部件

== 电控

硬件 固件组成

硬件就是电控盒中的电路板，是单片机系统

电控固件（ECU）就是运行在电控硬板上的程序

== 中控

=== 中控的组成
由硬件、固件组成

中控硬件指再中控盒子中的电路板、是嵌入式系统

中控固件(CCU)包含嵌入式系统固件（AP）和应用固件(CCU)，其中应用固件又分为驱动（LIB）和 (APP)

=== 中控的生命周期

开机过程

1. 开机，磁铁放到中控盒侧面小三角位置5s。
2. AP启动，开机后立即启动，启动完成大约30s，播放开机声。
3. APP启动，AP启动完成后立即启动APP,启动时会检测外设、加载LIB、初始化配置 启动大约10s

上线过程

1. 搜索运营商
2. 注册网络
3. 拨号
4. 连接服务器
5. 完成，完成后第二声开机声、发送报文 OLN CHK PWO HBT VER 上线大约10s

存活

存活时期可以接收指令、定时上报报文、时间触发上报等

关机

关机方式： 指令关机、掉电关机。

== 应用软件和工具

=== 中控插件
. modem
. gps
. gsenser
. gyroscope
. ble..

=== 测试工具

. 蓝牙全检工具
. 串口长测工具
. hawkeye

=== 应用

. app
. 小程序
. web

== 其他部件


=== 生产流程
. 电控生产，由电控厂家提供硬件、ECU，我们测试
. 中控生产
.. 由厂商提供中控硬件、AP和LIB
.. 由我们提供APP,并通过整包升级平台，根据车型、厂商、硬件条件为前提，将CCU、ECU、AP、BLE的版本信息以及下载地址合进一个json字典中，用于整包升级
.. 将整包程序发送给中控厂家合入AP中，交回我们测试验收
.. 然后中控厂商串口厂测 检查版本，外设功能、电控通信、蓝牙连接等，检测数据绑定imei存入数据库。
. 整车生产
.. 物料确认
.. 组装车辆
.. 车码绑定
.. 蓝牙全检 检查开闭锁，骑行等功能
.. 对不合格的车辆解绑重绑
. 装柜运输

docker run -d  --name=filebeat  --user=root --volume="/var/lib/docker/containers:/var/lib/docker/containers:ro" --volume="/var/run/docker.sock:/var/run/docker.sock:ro"  docker.elastic.co/beats/filebeat:6.5.4 filebeat -e -strict.perms=false  -E output.elasticsearch.hosts=["elasticsearch:9200"]

